version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379"
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "1337:80"
    depends_on:
      - redis